### ISSUE TITLE
My comment is shown as 2 hours ago despite it was posted just now

### ISSUE THREAD

**Issue by pioneer** [krawieck/lemmur#150]
See the screenshot.
![Screenshot_20210211-184454.jpg](https://user-images.githubusercontent.com/200538/107668614-88738400-6c99-11eb-9899-7e15e50c5dbd.jpg)

The APK is again the one taken from issue #138.

**Comment by pioneer** [comment]
Sorry, forgot to mention, here is the post https://lemmy.ml/post/53000

**Comment by shilangyu** [comment]
Looks like everything is shifted by 2h, not only your comment. Can you confirm that?

**Comment by pioneer** [comment]
Yes, posts are also shifted by 2h, I confirm.

**Comment by shilangyu** [comment]
@dessalines is there a reason why timestamps returned from the API do not contain any timezone information? I see the docs mention we should assume it is UTC, but why isn't this information in the ISO string? Wouldn't it be enough to append a `'Z'` to the string?

**Comment by dessalines** [comment]
For iso8601 the time zone is optional, (which is how our DB stores everything, all times in UTC with no offset). 

To me, if you're converting from utc to something else, it makes no sense to include that, which is why moment for example has its own utc parser: 

https://github.com/LemmyNet/lemmy-ui/blob/9e8d0b525abf2f75922d976dd875e7fa7e91c8ed/src/shared/components/moment-time.tsx#L36

If your parser requires it, you can always add that 'Z' on there.

**Comment by shilangyu** [comment]
Lack of a trailing `Z` implies local time which isn't the case here, so it will make every datetime parser trip up. There is a hidden context here which I don't think is good.

I guess I'll will need to inject a `Z` to every timestamp :/

**Comment by krawieck** [comment]
> For iso8601 the time zone is optional, (which is how our DB stores everything, all times in UTC with no offset).
> To me, if you're converting from utc to something else, it makes no sense to include that, which is why moment for example has its own utc parser:

Why not just include the `Z` at the end of the date? It's not going to be much of a difference on the backend, but it's going to make everyone's life easier. Even in your codebase I can see that you append Z to the end of the date to make it parsable, so why not just include it by default?

![2021-02-13 12 15 16](https://user-images.githubusercontent.com/10037914/107848628-3c3d5680-6df5-11eb-8443-e52bfadd6581.jpg)

Also it's not like we can't fix it or are too lazy or sth like that, we already have PR ready to merge. It's not about that, it's about the fact that every single person that is going to make an app for lemmy is going to encounter this issue and they are going to be confused because basically every other API returns UTC date with Z at the end. So why not just include it?

**Comment by dessalines** [comment]
It comes from us using a postgres column `without time zone` for all our time columns, storing them all in UTC instead of storing the timezone offets. We don't do any manipulation of that column, we just serialize it directly, which is why there's no timezone info with it. Possibly in the future we could switch all of those time columns to a `with time zone`, but for now just use either the `Z` method, or the https://pub.dev/documentation/intl/latest/intl/DateFormat/parseUtc.html method there. 

My codebase uses both, but in that utils I could've also used `moment.utc(utcDate).toDate()` to get a local date.
