### ISSUE TITLE
Support lemmy's UserSettings for default_sort_type and default_listing_type

### ISSUE THREAD

**Issue by dessalines** [krawieck/lemmur#156]
### Is your feature request related to a problem? Please describe.
My default view in lemmur is set to `Subscribed`, even though the remote setting is `All`.

### Describe the solution you'd like
For lemmur to support the `default_sort_type` and `default_listing_type` fields that come back from `GetSite.my_user`

Possibly also support saving user settings, but that could be a separate issue.

**Comment by shilangyu** [comment]
@tslocum thanks! I appreciate the offer to help. However doing this would require making some design decisions that I have not yet made. This belongs to a broader topic of caching in lemmur which I would like to think through before implementing it, thus I would like to wait with this issue.

**Comment by shilangyu** [comment]
We chose to go a slightly different route: these settings will be local to lemmur, but there will be an option import settings from an account into lemmur. 

We will explain this in more detail in the release post, but long story short supporting these settings on an account basis rather than global lemmur basis could be confusing for users
