### ISSUE TITLE
Unable to add instance running lemmy 0.9 (api v2)

### ISSUE THREAD

**Issue by c-cesar** [krawieck/lemmur#205]
### Device info

- OS: Android
- OS version: 10
- Device: Samsung s7

### Describe the bug
Using Lemmur 0.4.1 I'm unable to add lemmy 0.9 instance. Lemmur is now totally incompatible with API v2? As some instances still using it, there is a way to support boot APIs at least for some time?

BTW, the app is great. Congrats and thanks.

### Steps to reproduce
When trying to add a instance to login if I try to add a 0.9 instance I get the error "instance not found".
1. Go to Accounts
2. Click on 'Add Account'
3. paste a link to a 0.9 instance, like lemmy.cat

### Expected behavior
Add instance

**Comment by shilangyu** [comment]
Back when we migrated from API v1 to v2 we have thought about the possibility of supporting multiple API versions. This idea was abandoned for two reasons: lemmy devs recommended against it plus when we thought more about it we realized it would be a huge effort on our part. It would essentially mean checking on every step whether a given api version supports an action and then performing it differently if possible at all (then there's the problem of different API responses so every view would have to be conditionally rendered). I hope this gives you an idea why we can only support one version. We hope these problems will go away once lemmy hits v1, because for now whenever a new api version is released the previous one is completely removed, so we are also unable to stay on an old version.

Best help I can offer is: Nudge admins of these lemmy 0.9.0 instances to upgrade (AFAIK these upgrades have no downsides and required close to no effort), or stick to only instances using the same API version and then using the appropriate lemmur version (v0.3.0 for API v2, v0.4.1 for API v3)

Sorry for a disappointing answer and I hope this sheds some light on the situation
