### ISSUE TITLE
Updating version from F-Droid removes registered accounts

### ISSUE THREAD

**Issue by Porrumentzio** [krawieck/lemmur#213]
### Device info

- OS: Android based /e/OS
- OS version: Android 7.1.2
- Device: Xiaomi Redmi Note 4X

### Describe the bug
Updating Lemmur from F-Droid removes previously registered accounts, so each time I upgrade, I have to enter the account again.

### Steps to reproduce
1. Register a Lemmy account on Lemmur
2. Update Lemmur from F-Droid and the accounts on Lemmur will disappear

### Expected behavior
Account data should not be removed when upgrading Lemmur.

**Comment by shilangyu** [comment]
This sadly is not a bug but an expected effect after some updates. This won't happen after every update. We mention whether an update will log you out of all accounts in the [release notes](https://github.com/krawieck/lemmur/releases/tag/v0.4.2). This is due changes in the lemmy API and since it is still unstable we don't think it is worth writing migrating scripts after every change (if possible at all).

For more info about this particular release (v0.4.2) check https://lemmy.ml/post/60293
