### ISSUE TITLE
Can't log in to my account

### ISSUE THREAD

**Issue by McFranko** [krawieck/lemmur#233]
### Device info

- OS: Android Resurrection Remix
- OS version: 10
- Device: Oneplus 7 Pro
- Lemmur version: Latest on FDroid

### Describe the bug

Whenever I try to log into lemmy.ml  with what I'm sure is the right password, it doesn't work at says 

`LemmyApiException: password_incorrect`

I can login fine on the website.

### Steps to reproduce

1. Make an account on lemmy.ml
2. Try to log on with lemmur

### Expected behavior

I should be able to log into my account with the correct username and password.

### Screenshots/Screencasts

![Screenshot_20210718-094003347__01](https://user-images.githubusercontent.com/13605775/126075275-c14809f1-876c-46a6-9e25-97a33911aedc.jpg)

**Comment by krawieck** [comment]
Just to be sure, can you write your password into a notepad on your phone, copy it, then log in to lemmy in browser (by pasting it into the field), and then paste it into lemmur and try logging in in that way. I want you to do that because I don't know what methodology you used for determining if you typed in the right password.

If you still can't log in then I'd like you to say if your password has any characters that go outside of the ASCII range? That information will be useful when trying to fix this problem

**Comment by rikmeijer** [comment]
I am not able to login either to my lemmy.ml account, but I'm bot seeing any exception. The signin loader just keeps spinning forever.

**Comment by shilangyu** [comment]
@rikmeijer this is due to the new lemmy v0.12.0 release, we plan to release a compatible version very soon

**Comment by shilangyu** [comment]
Please let me know if this still persists on 0.6.0

**Comment by rikmeijer** [comment]
Seems fixed!!
